os: linux
language: shell
services:
  - docker
dist: "xenial",
jobs:
  include:
    - name: "checks"
      script:
        - docker run -v `pwd`:`pwd` -w `pwd` --cap-add=SYS_PTRACE -t rusdevops/bootstrap-cpp scripts/checks.sh
    - name: "tests"
      script:
        - docker run -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/tests.sh
    - name: "quality"
      script:
        - docker run -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/coverage.sh
      # The bot has gone...
      # - docker run --env-file .env -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/duplication.sh

notifications:
  email: false

branches:
  only:
    - master
    - main
